# if you ever see a segfault or other unexpected nondeterminism in this (or any other) code,
# the immediate muscle memory response should be to recompile with the following, and then
# rerun the failing use case:
# make clean && make CFLAGS="-Og -g -fno-inline -fsanitize=address,undefined"

# overrideable vars used in implicit make rules
CFLAGS ?= -Os
CPPFLAGS += -Wall -Wextra -Wshadow -Wmissing-prototypes
LDFLAGS += ${CFLAGS}

GIT_HASH := $(shell ((git diff --exit-code HEAD 1>/dev/null 2>/dev/null && git describe --always --tags --exact 2>/dev/null) || git describe --dirty --always 2>/dev/null) || printf 'n/a')
GIT_STAMP := $(shell TZ=UTC git log -1 --format=%cd --date=format-local:'%Y%m%dT%H%MZ' || printf 'n/a')
GIT_TIME := $(shell TZ=UTC git log -1 --format=%cd --date=format-local:'%sULL' || printf '0ULL')
CPPFLAGS += -DGIT_VERSION="\"$(GIT_HASH) ($(GIT_STAMP))\"" -DGIT_TIME=$(GIT_TIME)

# list of targets to build, generated from .c files containing a main() function:

TARGETS=shm_logger shm_to_pipe udp_to_shm

all : ${TARGETS}

# for each target, the list of objects to link, generated by recursively crawling include statements with a corresponding .c file:

shm_logger : shm_logger.o shared_memory_ringbuffer.o
shm_to_pipe : shm_to_pipe.o shared_memory_ringbuffer.o
udp_to_shm : udp_to_shm.o shared_memory_ringbuffer.o

# for each object, the list of headers it depends on, generated by recursively crawling include statements:

shared_memory_ringbuffer.o : shared_memory_ringbuffer.h
shm_logger.o : shared_memory_ringbuffer.h
shm_to_pipe.o : shared_memory_ringbuffer.h
udp_to_shm.o : shared_memory_ringbuffer.h

*.o : Makefile

install : udp_to_shm
	install -C udp_to_shm /usr/local/bin/
	install -C udp_to_shm.service /etc/systemd/system/ || true
	install -C cobs_to_shm.service /etc/systemd/system/ || true
	install -C shm_logger /usr/local/bin/
	install -C shm_to_pipe /usr/local/bin/
	install -C shm_logger.service /etc/systemd/system/ || true
	install -C 99-usb0.rules /etc/udev/rules.d/ || true
	udevadm control --reload-rules || true

uninstall :
	$(RM) /usr/local/bin/udp_to_shm
	$(RM) /usr/local/bin/shm_logger
	$(RM) /usr/local/bin/shm_to_pipe
	$(RM) /etc/systemd/system/udp_to_shm.service || true
	$(RM) /etc/systemd/system/shm_logger.service || true

clean :
	$(RM) -rf *.o *.dSYM ${TARGETS}
.PHONY: clean install uninstall all
